version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    environment:
      - ENVIRONMENT=development
    networks:
      - insight-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy_key_for_build}
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - insight-network

networks:
  insight-network:
    driver: bridge
